### ISSUE TITLE
Morning code review 09/09/2021

### ISSUE THREAD

**Issue by notlfish** [enionsouza/BonAppetit#22]

**Comment by notlfish** [comment]
Good job so far!
I would advise putting the code with the functionality you might be eventually interested in testing in files that don't load resources. Otherwise, you'll be fighting against webpack and jest

**Comment by enionsouza** [comment]
### Hi @notlfish!
It's always great to get feedback from you!
Thanks very much for taking the time to see our code. :pray: 
We'll definitely try to follow your wise advice, man...
![](https://media3.giphy.com/media/BYoRqTmcgzHcL9TCy1/giphy.gif)
